#!/usr/bin/env python
"""
phenny - An IRC Bot
Copyright 2008, Sean B. Palmer, inamidst.com
Licensed under the Eiffel Forum License 2.

http://inamidst.com/phenny/

Note: DO NOT EDIT THIS FILE.
Run ./phenny, then edit ~/.phenny/default.py
Then run ./phenny again
--
pyDerechiBot by ElGatoSaez
pyderechibot.cf - @pyDerechiBot
"""

import sys, os, imp, optparse
from textwrap import dedent as trim

dotdir = os.path.expanduser('~/.phenny')

def check_python_version(): 
   if sys.version_info < (2, 4): 
      error = 'Error: Requiere Python 2.4 o mas adelante, descárguelo desde www.python.org'
      print >> sys.stderr, error
      sys.exit(1)

def create_default_config(fn): 
   f = open(fn, 'w')
   print >> f, trim("""\
   nick = 'botDerechista'
   host = 'irc.ejemplo.net'
   channels = ['#ejemplo', '#test']
   owner = 'tunick'

   # password es la contraseña de NickServ, serverpass es la contraseña del Servidor
   # password = 'example'
   # serverpass = 'serverpass'

   # Estas personas pueden usar las funciones de admin.py
   admins = [owner, 'alguienqueconfies']
   # Pero admin.py está deshabilitado por defecto, como aparece acá
   exclude = ['admin']

   # Si quieres tomar una lista de módulos y quieres deshabilitarlos, prueba solo con los habilitados.
   # Usa "enable = ['example']", que toma precedencia a cuales deshabilitar
   # 
   # enable = []

   # Directorio de donde cargar el módulo
   # e.g. /path/to/my/modules
   extra = []

   # Cargar servicios
   external = { 
      '#conservative': ['!'], # allow all
      '#comunism': [], # allow none
      '*': ['!'] # default whitelist, allow all
   }

   # EOF
   """)
   f.close()

def create_default_config_file(dotdir):
   print 'Creating a default config file at ~/.phenny/default.py...'
   default = os.path.join(dotdir, 'default.py')
   create_default_config(default)

   print 'Done; now you can edit default.py, and run phenny! Enjoy.'
   sys.exit(0)

def create_dotdir(dotdir): 
   print 'Creating a config directory at ~/.phenny...'
   try: os.mkdir(dotdir)
   except Exception, e: 
      print >> sys.stderr, 'There was a problem creating %s:' % dotdir
      print >> sys.stderr, e.__class__, str(e)
      print >> sys.stderr, 'Please fix this and then run phenny again.'
      sys.exit(1)

   create_default_config_file(dotdir)

def check_dotdir(): 
   default = os.path.join(dotdir, 'default.py')

   if not os.path.isdir(dotdir): 
      create_dotdir(dotdir)
   elif not os.path.isfile(default): 
      create_default_config_file(dotdir)

def config_names(config): 
   config = config or 'default'

   def files(d): 
      names = os.listdir(d)
      return list(os.path.join(d, fn) for fn in names if fn.endswith('.py'))

   here = os.path.join('.', config)
   if os.path.isfile(here): 
      return [here]
   if os.path.isfile(here + '.py'): 
      return [here + '.py']
   if os.path.isdir(here): 
      return files(here)

   there = os.path.join(dotdir, config)
   if os.path.isfile(there): 
      return [there]
   if os.path.isfile(there + '.py'): 
      return [there + '.py']
   if os.path.isdir(there): 
      return files(there)

   print >> sys.stderr, "Error: Couldn't find a config file!"
   print >> sys.stderr, 'What happened to ~/.phenny/default.py?'
   sys.exit(1)

def main(argv=None): 
   # Step One: Parse The Command Line

   parser = optparse.OptionParser('%prog [options]')
   parser.add_option('-c', '--config', metavar='fn', 
      help='use this configuration file or directory')
   opts, args = parser.parse_args(argv)
   if args: print >> sys.stderr, 'Warning: ignoring spurious arguments'

   # Step Two: Check Dependencies

   check_python_version() # require python2.4 or later
   if not opts.config:
      check_dotdir() # require ~/.phenny, or make it and exit

   # Step Three: Load The Configurations

   config_modules = []
   for config_name in config_names(opts.config): 
      name = os.path.basename(config_name).split('.')[0] + '_config'
      module = imp.load_source(name, config_name)
      module.filename = config_name

      if not hasattr(module, 'prefix'): 
         module.prefix = r'\.'

      if not hasattr(module, 'name'): 
         module.name = 'uso pyDerechiBot, http://pyderechibot.cf'

      if not hasattr(module, 'port'): 
         module.port = 6667

      if not hasattr(module, 'password'): 
         module.password = None

      if module.host == 'irc.example.net': 
         error = ('Error: you must edit the config file first!\n' + 
                  "You're currently using %s" % module.filename)
         print >> sys.stderr, error
         sys.exit(1)

      config_modules.append(module)

   # Step Four: Load Phenny

   try: from __init__ import run
   except ImportError: 
      try: from phenny import run
      except ImportError: 
         print >> sys.stderr, "Error: Couldn't find phenny to import"
         sys.exit(1)

   # Step Five: Initialise And Run The Phennies

   # @@ ignore SIGHUP
   for config_module in config_modules: 
      run(config_module) # @@ thread this

if __name__ == '__main__': 
   main()
